// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vswtyacqrwxcxzimwaqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzd3R5YWNxcnd4Y3h6aW13YXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjM1MjYsImV4cCI6MjA2ODE5OTUyNn0.nGBG2SalvbUFJpWQvF5rIoh5_Woo7orxxoNKnX-ECxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});